use std::{
    collections::{BTreeMap, BTreeSet},
    fs,
    io::{self, Read},
    path::{Path, PathBuf},
};

use anyhow::{bail, Context, Result};
use clap::Parser;
use flate2::read::{DeflateDecoder, GzDecoder, ZlibDecoder};
use serde::Deserialize;
use serde_json::Value;

const MAX_DECODED_RESPONSE_BODY_BYTES: u64 = 64 * 1024 * 1024;

#[derive(Debug, Parser)]
#[command(name = "codex-provider-proxy-log-analyze")]
#[command(about = "Analyze exchange logs generated by codex-provider-proxy")]
struct Args {
    /// Directory that contains `*.meta.json` exchange log files.
    #[arg(short = 'd', long, default_value = "logs/exchanges")]
    dir: PathBuf,

    /// Include only exchanges with `started_unix_ms >= this value`.
    #[arg(short = 'f', long)]
    from_unix_ms: Option<u128>,

    /// Include only exchanges with `started_unix_ms <= this value`.
    #[arg(short = 't', long)]
    to_unix_ms: Option<u128>,

    /// Provider filter (exact match against the final provider or any retry-attempt provider).
    #[arg(short = 'p', long, value_delimiter = ',')]
    provider: Vec<String>,

    /// Model filter (exact match). Repeat or pass comma-separated values.
    #[arg(short = 'm', long, value_delimiter = ',')]
    model: Vec<String>,
}

#[derive(Debug, Default)]
struct AnalysisFilters {
    from_unix_ms: Option<u128>,
    to_unix_ms: Option<u128>,
    providers: BTreeSet<String>,
    models: BTreeSet<String>,
}

impl AnalysisFilters {
    fn from_args(args: &Args) -> Self {
        Self {
            from_unix_ms: args.from_unix_ms,
            to_unix_ms: args.to_unix_ms,
            providers: normalize_filter_values(&args.provider),
            models: normalize_filter_values(&args.model),
        }
    }

    fn matches_time(&self, started_unix_ms: Option<u128>) -> bool {
        if self.from_unix_ms.is_none() && self.to_unix_ms.is_none() {
            return true;
        }
        let Some(started) = started_unix_ms else {
            return false;
        };
        if let Some(from) = self.from_unix_ms {
            if started < from {
                return false;
            }
        }
        if let Some(to) = self.to_unix_ms {
            if started > to {
                return false;
            }
        }
        true
    }

    fn matches_provider<'a>(
        &self,
        provider: Option<&str>,
        attempt_providers: impl IntoIterator<Item = &'a str>,
    ) -> bool {
        if self.providers.is_empty() {
            return true;
        }
        provider.is_some_and(|p| self.providers.contains(p))
            || attempt_providers
                .into_iter()
                .any(|provider| self.providers.contains(provider))
    }

    fn has_model_filter(&self) -> bool {
        !self.models.is_empty()
    }

    fn matches_model(&self, model: &str) -> bool {
        if self.models.is_empty() {
            return true;
        }
        self.models.contains(model)
    }
}

fn normalize_filter_values(values: &[String]) -> BTreeSet<String> {
    values
        .iter()
        .map(|v| v.trim())
        .filter(|v| !v.is_empty())
        .map(ToOwned::to_owned)
        .collect()
}

#[derive(Debug, Default)]
struct AnalysisStats {
    exchanges_total: u64,
    exchanges_selected: u64,
    filtered_out_time: u64,
    filtered_out_provider: u64,
    filtered_out_model: u64,
    meta_parse_errors: u64,
    response_body_missing: u64,
    completed_response_found: u64,
    usage_found: u64,
    usage_parse_errors: u64,
    upstream_latency_ms: Vec<u128>,
    total_duration_ms: Vec<u128>,
    input_tokens: u64,
    output_tokens: u64,
    total_tokens: u64,
    cached_tokens: u64,
    input_categories: BTreeMap<String, u64>,
    output_categories: BTreeMap<String, u64>,
}

#[derive(Debug, Deserialize)]
struct ExchangeMeta {
    #[serde(default)]
    started_unix_ms: Option<u128>,
    #[serde(default)]
    provider: Option<String>,
    #[serde(default)]
    attempts: Vec<ExchangeAttemptMeta>,
    #[serde(default)]
    upstream_latency_ms: Option<u128>,
    #[serde(default)]
    total_duration_ms: Option<u128>,
    #[serde(default)]
    body_compression: Option<String>,
    #[serde(default)]
    files: ExchangeMetaFiles,
}

#[derive(Debug, Default, Deserialize)]
struct ExchangeAttemptMeta {
    #[serde(default)]
    provider: Option<String>,
}

#[derive(Debug, Default, Deserialize)]
struct ExchangeMetaFiles {
    #[serde(default)]
    request_body: String,
    #[serde(default)]
    response_headers: String,
    #[serde(default)]
    response_body: String,
}

#[derive(Debug, Default)]
struct UsageSnapshot {
    input_tokens: u64,
    output_tokens: u64,
    total_tokens: u64,
    cached_tokens: u64,
    input_categories: BTreeMap<String, u64>,
    output_categories: BTreeMap<String, u64>,
}

pub fn run() -> Result<()> {
    let args = Args::parse();
    let filters = AnalysisFilters::from_args(&args);

    let mut meta_files = collect_meta_files(&args.dir)?;
    meta_files.sort();

    let mut stats = AnalysisStats {
        exchanges_total: u64::try_from(meta_files.len()).unwrap_or(u64::MAX),
        ..AnalysisStats::default()
    };

    for meta_path in meta_files {
        if let Err(err) = analyze_exchange(&meta_path, &filters, &mut stats) {
            stats.meta_parse_errors = stats.meta_parse_errors.saturating_add(1);
            eprintln!("warn: skip {}: {err}", meta_path.display());
        }
    }

    print_report(&filters, &stats);
    Ok(())
}

fn collect_meta_files(dir: &Path) -> Result<Vec<PathBuf>> {
    let entries = fs::read_dir(dir).with_context(|| format!("read dir {}", dir.display()))?;
    let mut out = Vec::new();
    for entry in entries {
        let entry = entry.with_context(|| format!("read entry in {}", dir.display()))?;
        let path = entry.path();
        if !path.is_file() {
            continue;
        }
        if path
            .file_name()
            .and_then(|n| n.to_str())
            .is_some_and(|n| n.ends_with(".meta.json"))
        {
            out.push(path);
        }
    }
    Ok(out)
}

fn analyze_exchange(
    meta_path: &Path,
    filters: &AnalysisFilters,
    stats: &mut AnalysisStats,
) -> Result<()> {
    let meta_bytes =
        fs::read(meta_path).with_context(|| format!("read meta {}", meta_path.display()))?;
    let meta: ExchangeMeta = serde_json::from_slice(&meta_bytes)
        .with_context(|| format!("parse meta {}", meta_path.display()))?;

    if !filters.matches_time(meta.started_unix_ms) {
        stats.filtered_out_time = stats.filtered_out_time.saturating_add(1);
        return Ok(());
    }
    if !filters.matches_provider(
        meta.provider.as_deref(),
        meta.attempts
            .iter()
            .filter_map(|attempt| attempt.provider.as_deref()),
    ) {
        stats.filtered_out_provider = stats.filtered_out_provider.saturating_add(1);
        return Ok(());
    }

    let stem = meta_path
        .file_name()
        .and_then(|n| n.to_str())
        .and_then(|n| n.strip_suffix(".meta.json"))
        .with_context(|| format!("extract stem from {}", meta_path.display()))?;

    let request_body_path = resolve_logged_path(
        meta_path,
        &meta.files.request_body,
        &format!("{stem}.request_body.bin"),
    );
    let response_headers_path = resolve_logged_path(
        meta_path,
        &meta.files.response_headers,
        &format!("{stem}.response_headers.txt"),
    );
    let response_body_path = resolve_logged_path(
        meta_path,
        &meta.files.response_body,
        &format!("{stem}.response_body.bin"),
    );

    let mut response_for_usage: Option<Value> = None;
    if filters.has_model_filter() {
        let model =
            extract_model_from_request_body(&request_body_path, meta.body_compression.as_deref())
                .or_else(|| {
                    if !response_body_path.exists() {
                        return None;
                    }
                    match extract_completed_response_from_log(
                        &response_body_path,
                        &response_headers_path,
                        meta.body_compression.as_deref(),
                    ) {
                        Ok(response) => {
                            response_for_usage = response.clone();
                            response.and_then(|r| extract_model_from_response(&r))
                        }
                        Err(err) => {
                            stats.usage_parse_errors = stats.usage_parse_errors.saturating_add(1);
                            eprintln!(
                                "warn: parse response body {}: {err}",
                                response_body_path.display()
                            );
                            None
                        }
                    }
                });

        if model
            .as_deref()
            .is_none_or(|name| !filters.matches_model(name))
        {
            stats.filtered_out_model = stats.filtered_out_model.saturating_add(1);
            return Ok(());
        }
    }

    stats.exchanges_selected = stats.exchanges_selected.saturating_add(1);

    if let Some(latency) = meta
        .upstream_latency_ms
        .or_else(|| parse_latency_from_response_headers(&response_headers_path))
    {
        stats.upstream_latency_ms.push(latency);
    }
    if let Some(total) = meta.total_duration_ms {
        stats.total_duration_ms.push(total);
    }

    if !response_body_path.exists() {
        stats.response_body_missing = stats.response_body_missing.saturating_add(1);
        return Ok(());
    }

    let response = match response_for_usage {
        Some(response) => Some(response),
        None => {
            let parsed = extract_completed_response_from_log(
                &response_body_path,
                &response_headers_path,
                meta.body_compression.as_deref(),
            );
            match parsed {
                Ok(v) => v,
                Err(err) => {
                    stats.usage_parse_errors = stats.usage_parse_errors.saturating_add(1);
                    eprintln!(
                        "warn: parse response body {}: {err}",
                        response_body_path.display()
                    );
                    None
                }
            }
        }
    };

    let Some(response) = response else {
        return Ok(());
    };
    stats.completed_response_found = stats.completed_response_found.saturating_add(1);

    let Some(usage) = extract_usage_snapshot(&response) else {
        return Ok(());
    };
    stats.usage_found = stats.usage_found.saturating_add(1);
    merge_usage(stats, usage);

    Ok(())
}

fn resolve_logged_path(meta_path: &Path, configured: &str, fallback_file: &str) -> PathBuf {
    let configured = configured.trim();
    if configured.is_empty() {
        return meta_path.with_file_name(fallback_file);
    }

    let direct = PathBuf::from(configured);
    if direct.is_absolute() {
        return direct;
    }

    meta_path
        .parent()
        .unwrap_or_else(|| Path::new("."))
        .join(direct)
}

fn parse_latency_from_response_headers(path: &Path) -> Option<u128> {
    let text = fs::read_to_string(path).ok()?;
    for line in text.lines() {
        let line = line.trim();
        if let Some(rest) = line.strip_prefix("latency_ms:") {
            if let Ok(v) = rest.trim().parse::<u128>() {
                return Some(v);
            }
        }
    }
    None
}

fn extract_model_from_request_body(path: &Path, body_compression: Option<&str>) -> Option<String> {
    let bytes = read_logged_body(path, body_compression).ok()?;
    if bytes.is_empty() {
        return None;
    }
    let json: Value = serde_json::from_slice(&bytes).ok()?;
    json.get("model")
        .and_then(|v| v.as_str())
        .map(ToOwned::to_owned)
}

fn extract_model_from_response(response: &Value) -> Option<String> {
    response
        .get("model")
        .and_then(|v| v.as_str())
        .map(ToOwned::to_owned)
}

fn extract_completed_response_from_log(
    path: &Path,
    response_headers_path: &Path,
    body_compression: Option<&str>,
) -> Result<Option<Value>> {
    let bytes = read_logged_response_body(path, response_headers_path, body_compression)
        .with_context(|| format!("read response body {}", path.display()))?;
    if bytes.is_empty() {
        return Ok(None);
    }

    let text = String::from_utf8_lossy(&bytes);
    if looks_like_sse(&text) {
        return Ok(extract_completed_response_from_sse(&text));
    }

    match serde_json::from_str::<Value>(&text) {
        Ok(json) => Ok(json
            .get("response")
            .cloned()
            .or(Some(json))
            .filter(|v| v.is_object())),
        Err(_) => Ok(None),
    }
}

fn read_logged_response_body(
    path: &Path,
    response_headers_path: &Path,
    body_compression: Option<&str>,
) -> Result<Vec<u8>> {
    let body = read_logged_body(path, body_compression)?;
    let encodings = read_response_content_encodings(response_headers_path)?;
    decode_content_encodings(body, &encodings).with_context(|| {
        format!(
            "decode content encoding from response headers {}",
            response_headers_path.display()
        )
    })
}

fn read_logged_body(path: &Path, body_compression: Option<&str>) -> Result<Vec<u8>> {
    let is_zstd = body_compression
        .map(|v| v.eq_ignore_ascii_case("zstd"))
        .unwrap_or(false)
        || path
            .extension()
            .and_then(|v| v.to_str())
            .is_some_and(|v| v.eq_ignore_ascii_case("zst"));
    if is_zstd {
        let file = fs::File::open(path).with_context(|| format!("open {}", path.display()))?;
        let decoder = zstd::stream::read::Decoder::new(file)
            .with_context(|| format!("open zstd decoder for {}", path.display()))?;
        let bytes = read_limited(decoder, "logged body")
            .with_context(|| format!("decode zstd {}", path.display()))?;
        return Ok(bytes);
    }
    let file = fs::File::open(path).with_context(|| format!("open {}", path.display()))?;
    read_limited(file, "logged body").with_context(|| format!("read {}", path.display()))
}

fn read_response_content_encodings(path: &Path) -> Result<Vec<String>> {
    if !path.exists() {
        return Ok(Vec::new());
    }

    let headers = fs::read_to_string(path)
        .with_context(|| format!("read response headers {}", path.display()))?;
    let mut encodings = Vec::new();
    for line in headers.lines() {
        let Some((name, value)) = line.split_once(':') else {
            continue;
        };
        if !name.trim().eq_ignore_ascii_case("content-encoding") {
            continue;
        }
        for encoding in value.split(',') {
            let encoding = encoding.trim();
            if encoding.is_empty() {
                bail!("empty Content-Encoding value in {}", path.display());
            }
            encodings.push(encoding.to_ascii_lowercase());
        }
    }
    Ok(encodings)
}

fn decode_content_encodings(mut body: Vec<u8>, encodings: &[String]) -> Result<Vec<u8>> {
    // Content codings are applied in header order and therefore decoded in reverse order.
    for encoding in encodings.iter().rev() {
        body = decode_one_content_encoding(body, encoding)?;
    }
    Ok(body)
}

fn decode_one_content_encoding(body: Vec<u8>, encoding: &str) -> Result<Vec<u8>> {
    match encoding {
        "identity" => Ok(body),
        "gzip" | "x-gzip" => Ok(read_decoded_limited(GzDecoder::new(body.as_slice()))?),
        "deflate" => decode_deflate(&body),
        "br" => Ok(read_decoded_limited(brotli::Decompressor::new(
            body.as_slice(),
            4096,
        ))?),
        "zstd" => {
            let decoder = zstd::stream::read::Decoder::new(body.as_slice())?;
            Ok(read_decoded_limited(decoder)?)
        }
        _ => bail!("unsupported content encoding {encoding:?}"),
    }
}

fn decode_deflate(body: &[u8]) -> Result<Vec<u8>> {
    match read_decoded_limited(ZlibDecoder::new(body)) {
        Ok(decoded) => Ok(decoded),
        Err(zlib_err) => read_decoded_limited(DeflateDecoder::new(body)).map_err(|raw_err| {
            anyhow::anyhow!(
                "failed to decode deflate content with zlib ({zlib_err}) or raw deflate ({raw_err})"
            )
        }),
    }
}

fn read_decoded_limited<R: Read>(reader: R) -> io::Result<Vec<u8>> {
    read_limited(reader, "decoded response")
}

fn read_limited<R: Read>(reader: R, subject: &str) -> io::Result<Vec<u8>> {
    let mut decoded = Vec::new();
    let mut reader = reader.take(MAX_DECODED_RESPONSE_BODY_BYTES.saturating_add(1));
    reader.read_to_end(&mut decoded)?;
    if u64::try_from(decoded.len()).unwrap_or(u64::MAX) > MAX_DECODED_RESPONSE_BODY_BYTES {
        return Err(io::Error::new(
            io::ErrorKind::InvalidData,
            format!("{subject} exceeds the {MAX_DECODED_RESPONSE_BODY_BYTES}-byte analysis limit"),
        ));
    }
    Ok(decoded)
}

fn looks_like_sse(payload: &str) -> bool {
    payload.lines().any(|line| {
        let line = line.trim_start();
        line.starts_with("event:") || line.starts_with("data:")
    })
}

fn extract_completed_response_from_sse(payload: &str) -> Option<Value> {
    let mut current_event: Option<String> = None;
    let mut data_lines: Vec<String> = Vec::new();
    let mut completed: Option<Value> = None;

    for line in payload.lines() {
        let line = line.trim_end_matches('\r');
        if line.is_empty() {
            handle_sse_event(&current_event, &data_lines, &mut completed);
            current_event = None;
            data_lines.clear();
            continue;
        }
        if let Some(rest) = line.strip_prefix("event:") {
            current_event = Some(rest.trim().to_string());
            continue;
        }
        if let Some(rest) = line.strip_prefix("data:") {
            data_lines.push(rest.trim_start().to_string());
            continue;
        }
    }

    if current_event.is_some() || !data_lines.is_empty() {
        handle_sse_event(&current_event, &data_lines, &mut completed);
    }
    completed
}

fn handle_sse_event(event: &Option<String>, data_lines: &[String], completed: &mut Option<Value>) {
    if data_lines.is_empty() {
        return;
    }
    let data = data_lines.join("\n");
    let data = data.trim();
    if data.is_empty() || data == "[DONE]" {
        return;
    }

    let Ok(json) = serde_json::from_str::<Value>(data) else {
        return;
    };

    if let Some(response) = json.get("response") {
        *completed = Some(response.clone());
        return;
    }
    if event.as_deref() == Some("response.completed") {
        *completed = Some(json);
    }
}

fn extract_usage_snapshot(response: &Value) -> Option<UsageSnapshot> {
    let usage = response.get("usage")?.as_object()?;
    let mut out = UsageSnapshot {
        input_tokens: usage
            .get("input_tokens")
            .and_then(value_to_u64)
            .unwrap_or_default(),
        output_tokens: usage
            .get("output_tokens")
            .and_then(value_to_u64)
            .unwrap_or_default(),
        total_tokens: usage
            .get("total_tokens")
            .and_then(value_to_u64)
            .unwrap_or_default(),
        ..UsageSnapshot::default()
    };

    if let Some(input_details) = usage.get("input_tokens_details") {
        out.input_categories = extract_numeric_map(input_details);
        out.cached_tokens = out
            .input_categories
            .get("cached_tokens")
            .copied()
            .unwrap_or_default();
    }
    if let Some(output_details) = usage.get("output_tokens_details") {
        out.output_categories = extract_numeric_map(output_details);
    }
    Some(out)
}

fn extract_numeric_map(value: &Value) -> BTreeMap<String, u64> {
    let mut out = BTreeMap::new();
    let Some(obj) = value.as_object() else {
        return out;
    };
    for (k, v) in obj {
        if let Some(n) = value_to_u64(v) {
            out.insert(k.clone(), n);
        }
    }
    out
}

fn value_to_u64(value: &Value) -> Option<u64> {
    if let Some(v) = value.as_u64() {
        return Some(v);
    }
    if let Some(v) = value.as_i64() {
        if v >= 0 {
            return u64::try_from(v).ok();
        }
    }
    None
}

fn merge_usage(stats: &mut AnalysisStats, usage: UsageSnapshot) {
    stats.input_tokens = stats.input_tokens.saturating_add(usage.input_tokens);
    stats.output_tokens = stats.output_tokens.saturating_add(usage.output_tokens);
    stats.total_tokens = stats.total_tokens.saturating_add(usage.total_tokens);
    stats.cached_tokens = stats.cached_tokens.saturating_add(usage.cached_tokens);

    for (k, v) in usage.input_categories {
        let slot = stats.input_categories.entry(k).or_default();
        *slot = slot.saturating_add(v);
    }
    for (k, v) in usage.output_categories {
        let slot = stats.output_categories.entry(k).or_default();
        *slot = slot.saturating_add(v);
    }
}

fn print_report(filters: &AnalysisFilters, stats: &AnalysisStats) {
    println!("filters.from_unix_ms={}", option_u128(filters.from_unix_ms));
    println!("filters.to_unix_ms={}", option_u128(filters.to_unix_ms));
    println!(
        "filters.providers={}",
        if filters.providers.is_empty() {
            "(any)".to_string()
        } else {
            filters
                .providers
                .iter()
                .cloned()
                .collect::<Vec<_>>()
                .join(",")
        }
    );
    println!(
        "filters.models={}",
        if filters.models.is_empty() {
            "(any)".to_string()
        } else {
            filters.models.iter().cloned().collect::<Vec<_>>().join(",")
        }
    );
    println!();

    println!("exchanges_total={}", stats.exchanges_total);
    println!("exchanges_selected={}", stats.exchanges_selected);
    println!("filtered_out_time={}", stats.filtered_out_time);
    println!("filtered_out_provider={}", stats.filtered_out_provider);
    println!("filtered_out_model={}", stats.filtered_out_model);
    println!("meta_parse_errors={}", stats.meta_parse_errors);
    println!("response_body_missing={}", stats.response_body_missing);
    println!(
        "completed_response_found={}",
        stats.completed_response_found
    );
    println!("usage_found={}", stats.usage_found);
    println!("usage_parse_errors={}", stats.usage_parse_errors);
    println!();

    println!("tokens.input_total={}", stats.input_tokens);
    println!("tokens.output_total={}", stats.output_tokens);
    println!("tokens.total={}", stats.total_tokens);
    println!("tokens.cached={}", stats.cached_tokens);
    if stats.input_tokens > 0 {
        let ratio = (stats.cached_tokens as f64 / stats.input_tokens as f64) * 100.0;
        println!("tokens.cache_ratio={ratio:.2}%");
    } else {
        println!("tokens.cache_ratio=n/a");
    }
    println!();

    println!("tokens.input_categories:");
    if stats.input_categories.is_empty() {
        println!("  (none)");
    } else {
        for (k, v) in &stats.input_categories {
            println!("  {k}={v}");
        }
    }
    println!("tokens.output_categories:");
    if stats.output_categories.is_empty() {
        println!("  (none)");
    } else {
        for (k, v) in &stats.output_categories {
            println!("  {k}={v}");
        }
    }
    println!();

    print_latency_stats("latency.upstream_ms", &stats.upstream_latency_ms);
    print_latency_stats("latency.total_duration_ms", &stats.total_duration_ms);
}

fn option_u128(value: Option<u128>) -> String {
    value
        .map(|v| v.to_string())
        .unwrap_or_else(|| "(none)".to_string())
}

fn print_latency_stats(label: &str, values: &[u128]) {
    if values.is_empty() {
        println!("{label}.count=0");
        return;
    }

    let mut sorted = values.to_vec();
    sorted.sort_unstable();
    let count = sorted.len();
    let min = sorted[0];
    let max = sorted[count - 1];
    let p50 = percentile_nearest_rank(&sorted, 0.50);
    let p95 = percentile_nearest_rank(&sorted, 0.95);
    let sum: u128 = sorted.iter().copied().sum();
    let avg = sum as f64 / count as f64;

    println!("{label}.count={count}");
    println!("{label}.avg={avg:.2}");
    println!("{label}.min={min}");
    println!("{label}.p50={p50}");
    println!("{label}.p95={p95}");
    println!("{label}.max={max}");
}

fn percentile_nearest_rank(sorted: &[u128], q: f64) -> u128 {
    if sorted.is_empty() {
        return 0;
    }
    let n = sorted.len();
    let rank = (q * n as f64).ceil() as usize;
    let idx = rank.saturating_sub(1).min(n - 1);
    sorted[idx]
}

#[cfg(test)]
mod tests {
    use std::{
        fs,
        io::{self, Read},
        path::Path,
        time::{Duration, SystemTime, UNIX_EPOCH},
    };

    use serde_json::json;

    use super::{
        extract_completed_response_from_log, extract_completed_response_from_sse,
        extract_usage_snapshot, normalize_filter_values, read_logged_body, resolve_logged_path,
        AnalysisFilters, ExchangeAttemptMeta, MAX_DECODED_RESPONSE_BODY_BYTES,
    };

    #[test]
    fn resolves_relative_logged_path_against_metadata_parent() {
        let meta_path = Path::new("logs/exchanges/1700000000000_req_1.meta.json");

        let resolved = resolve_logged_path(meta_path, "bodies/response.bin", "fallback.bin");

        assert_eq!(resolved, Path::new("logs/exchanges/bodies/response.bin"));
    }

    #[test]
    fn rejects_raw_logged_body_over_limit() {
        let path = temp_file_path("raw-over-limit", "bin");
        let file = fs::File::create(&path).expect("create sparse body");
        file.set_len(MAX_DECODED_RESPONSE_BODY_BYTES + 1)
            .expect("size sparse body");

        let error = read_logged_body(&path, None).expect_err("oversized raw body should fail");
        let error = format!("{error:#}");

        assert!(
            error.contains("logged body exceeds the 67108864-byte analysis limit"),
            "unexpected error: {error}"
        );
        let _ = fs::remove_file(path);
    }

    #[test]
    fn rejects_zstd_logged_body_decoding_over_limit() {
        let path = temp_file_path("zstd-over-limit", "bin.zst");
        let file = fs::File::create(&path).expect("create compressed body");
        let mut encoder = zstd::stream::write::Encoder::new(file, 1).expect("create encoder");
        io::copy(
            &mut io::repeat(0).take(MAX_DECODED_RESPONSE_BODY_BYTES + 1),
            &mut encoder,
        )
        .expect("encode oversized body");
        encoder.finish().expect("finish encoder");

        let error =
            read_logged_body(&path, Some("zstd")).expect_err("oversized decoded body should fail");
        let error = format!("{error:#}");

        assert!(
            error.contains("logged body exceeds the 67108864-byte analysis limit"),
            "unexpected error: {error}"
        );
        let _ = fs::remove_file(path);
    }

    #[test]
    fn extracts_response_from_completed_event() {
        let sse = concat!(
            "event: response.created\n",
            "data: {\"type\":\"response.created\"}\n\n",
            "event: response.completed\n",
            "data: {\"type\":\"response.completed\",\"response\":{\"id\":\"resp_1\",\"usage\":{\"input_tokens\":10}}}\n\n",
            "data: [DONE]\n\n"
        );
        let response = extract_completed_response_from_sse(sse).expect("response exists");
        assert_eq!(response.get("id").and_then(|v| v.as_str()), Some("resp_1"));
    }

    #[test]
    fn extracts_usage_categories() {
        let response = json!({
            "id": "resp_1",
            "usage": {
                "input_tokens": 100,
                "output_tokens": 20,
                "total_tokens": 120,
                "input_tokens_details": {
                    "cached_tokens": 40,
                    "text_tokens": 60
                },
                "output_tokens_details": {
                    "reasoning_tokens": 7,
                    "text_tokens": 13
                }
            }
        });
        let usage = extract_usage_snapshot(&response).expect("usage exists");
        assert_eq!(usage.input_tokens, 100);
        assert_eq!(usage.cached_tokens, 40);
        assert_eq!(usage.input_categories.get("text_tokens"), Some(&60));
        assert_eq!(usage.output_categories.get("reasoning_tokens"), Some(&7));
    }

    #[test]
    fn filter_normalization_trims_and_dedups() {
        let values = vec![
            " a ".to_string(),
            "a".to_string(),
            "".to_string(),
            "b".to_string(),
        ];
        let set = normalize_filter_values(&values);
        assert!(set.contains("a"));
        assert!(set.contains("b"));
        assert_eq!(set.len(), 2);
    }

    #[test]
    fn time_filter_requires_started_when_active() {
        let f = AnalysisFilters {
            from_unix_ms: Some(10),
            to_unix_ms: Some(20),
            ..AnalysisFilters::default()
        };
        assert!(!f.matches_time(None));
        assert!(f.matches_time(Some(10)));
        assert!(f.matches_time(Some(15)));
        assert!(f.matches_time(Some(20)));
        assert!(!f.matches_time(Some(9)));
        assert!(!f.matches_time(Some(21)));
    }

    #[test]
    fn provider_filter_matches_final_provider() {
        let mut providers = std::collections::BTreeSet::new();
        providers.insert("provider_b".to_string());
        let filters = AnalysisFilters {
            providers,
            ..AnalysisFilters::default()
        };

        assert!(filters.matches_provider(Some("provider_b"), std::iter::empty()));
        assert!(!filters.matches_provider(Some("provider_a"), std::iter::empty()));
    }

    #[test]
    fn provider_filter_matches_attempt_provider() {
        let mut providers = std::collections::BTreeSet::new();
        providers.insert("provider_a".to_string());
        let filters = AnalysisFilters {
            providers,
            ..AnalysisFilters::default()
        };
        let attempts = [
            ExchangeAttemptMeta {
                provider: Some("provider_a".to_string()),
            },
            ExchangeAttemptMeta {
                provider: Some("provider_b".to_string()),
            },
        ];

        assert!(filters.matches_provider(
            Some("provider_b"),
            attempts
                .iter()
                .filter_map(|attempt| attempt.provider.as_deref()),
        ));
    }

    #[test]
    fn reads_zstd_compressed_response_body() {
        let path = temp_file_path("zstd", "response_body.bin.zst");
        let response_headers_path = temp_file_path("zstd", "response_headers.txt");
        let payload = r#"{"response":{"id":"resp_zstd","usage":{"input_tokens":1}}}"#;
        let upstream_encoded =
            zstd::stream::encode_all(payload.as_bytes(), 3).expect("encode upstream zstd");
        let stored =
            zstd::stream::encode_all(upstream_encoded.as_slice(), 3).expect("encode exchange zstd");
        fs::write(&path, stored).expect("write zstd payload");
        fs::write(&response_headers_path, "content-encoding: zstd\n")
            .expect("write response headers");

        let response =
            extract_completed_response_from_log(&path, &response_headers_path, Some("zstd"))
                .expect("extract")
                .expect("response exists");
        assert_eq!(
            response.get("id").and_then(|v| v.as_str()),
            Some("resp_zstd")
        );

        let _ = fs::remove_file(&path);
        let _ = fs::remove_file(&response_headers_path);
    }

    fn temp_file_path(label: &str, extension: &str) -> std::path::PathBuf {
        let unique = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap_or_else(|_| Duration::from_secs(0))
            .as_nanos();
        std::env::temp_dir().join(format!(
            "proxyctl-log-analyze-{label}-{}-{unique}.{extension}",
            std::process::id()
        ))
    }
}
